package entities;
// Generated Jun 14, 2016 1:07:24 AM by Hibernate Tools 4.3.1



/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {
     private String userName;
     private String pass;
     private String email;
     private Boolean changedPass;

    public Admin() {
    }

	
    public Admin(String userName, String pass, String email) {
        this.userName = userName;
        this.pass = pass;
        this.email = email;
        changedPass=false;
    }
    public Admin(String userName, String pass, String email, Boolean changedPass) {
       this.userName = userName;
       this.pass = pass;
       this.email = email;
       this.changedPass = changedPass;
    }
   
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Boolean getChangedPass() {
        return this.changedPass;
    }
    
    public void setChangedPass(Boolean changedPass) {
        this.changedPass = changedPass;
    }




}


