package entities;
// Generated May 9, 2016 8:04:06 PM by Hibernate Tools 4.3.1



/**
 * Admin generated by hbm2java
 */
public class Admin  implements java.io.Serializable {


     private String userName;
     private String pass;
     private String email;

    public Admin() {
    }

    public Admin(String userName, String pass, String email) {
       this.userName = userName;
       this.pass = pass;
       this.email = email;
    }
   
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


